<?php
    // $options=$block->getmanufacturer();
    $options=$block->getcategories();
    // foreach ($options as $option) {
    //     echo $option->getValue() . ' -> ' . $option->getLabel() . ' '.$option->getUrl() .'</br>';
    // }
    $alphas = range('A', 'Z');
    $manufacturerfilter=array();
    foreach($alphas as $alpha){
        $k=0;
	    foreach ($options as $option) {
    		if(strtoupper(substr($option->getName(), 0,1))==$alpha){
    		    $manufacturerfilter[$alpha][$k] = $option;
    		  //  $manufacturerfilter[$alpha][$k]['url'] = $option->getUrl();
    			$k++;
    		}
	    }
    }
    $alflag =false;
    $k=0;
    foreach ($options as $option) {
        foreach($alphas as $alpha){
            if(strtoupper(substr($option->getName(), 0,1))==$alpha){
                $alflag = true;
                break;
            }
        }
        if(!$alflag) {
            $manufacturerfilter['al'][$k] = $option;
            // $manufacturerfilter['al'][$k]['url'] = $option->getUrl();
            $k++;
        }
    }
    $opt=array();
    foreach ($options as $option) {
         $opt[$option->getUrl()] = $option->getName();
    }
    // echo $manufacturerfilter['A'][0];
?>

<div class="brand-searcher">
    <div class="input-box">
        <div class="ambrands-search-wrapper">
            <h3>Quick Search By Manufacturer Name</h3>
            <input type="hidden" value='<?php echo json_encode($opt);?>' id="caters"/>
            <div class="input-outer">
                <input href="#" type="text" onkeyup="searchBrands(this.value)" class="input-text ambrands-search-input" id="ambrands-search-input" placeholder="Search Manufacturer Name" value="">
                <div id="livesearch">
                </div>
            </div>
        </div>
    </div>
    <style>
        
    </style>
    <script type="text/javascript">
    brands = JSON.parse(document.getElementById("caters").value);
    function searchBrands(str) {
        var resDropDown = document.getElementById("livesearch");
        str = str.trim().toLowerCase();
        if (str.length==0) {
            resDropDown.style.display = "none";
            return;
        }
        var foundBrands = {};

        for(var url in brands) {
            if (brands[url].toLowerCase().indexOf(str) != -1){
                foundBrands[url] = brands[url];
            }
        }
        if (!Object.keys(foundBrands).length) {
            resDropDown.style.display = "none";
        } else {
            var result = '';
            for(var url in foundBrands) {
                result += '<a href="' + url +'">'
                    + foundBrands[url] + '</a>';
            }
            resDropDown.style.display = "block";
            resDropDown.innerHTML = result;
        }
    }
</script>
</div>
<div class="content">
    <div class="brands-filters">
        <div class="letters">
            <div class="letters-box">
                <a href="javascript:void(0)" class="letter letter-al" data-letter="al">#</a>
                <?php
                    
                    foreach (range('A', 'Z') as $letter) {
                
                    echo "<a href='javascript:void(0)' class='letter letter-".$letter."' data-letter='".$letter."'>". $letter."</a>";
                
                    }
                ?>
            </div>
            <div class="letters-box" id="clear-filter" style="">
                <a href="javascript:void(0)" class="letter letter-all" data-ambrands-js="filter-letter" title="Clear filter">Clear filter</a>
            </div>
        </div>
    </div>
    <div class="brand-listing" data-collapsible="true">
        <dl class="brands-letter letter-al" data-letter="al" role="tablist" style="display: block;">
            <dt class="letter" role="tab" aria-selected="true" aria-expanded="true" tabindex="0"><span class="icon-open" data-role="icons" style="display: none;"></span>
                <span class="title">#</span>
            </dt>
            <dd class="content" role="tabpanel" aria-hidden="false" style="display: block;">
                <ul class="bare-list">
                    <?php
                    if(isset($manufacturerfilter['al'])){
                    foreach($manufacturerfilter['al'] as $manu){
                    ?>
                    <li class="brand-item">
                    <a href="<?php echo $manu->getUrl(); ?>" class="item" title="<?php echo $manu->getName(); ?>"><?php echo $manu->getName(); ?></a>
                    </li>
                    <?php
                    }
                    }
                    ?>
                </ul>
            </dd>
        </dl>
    </div>
    <?php
    foreach (range('A', 'Z') as $letter) {
    ?>
    <div class="brand-listing" data-collapsible="true">
        <dl class="brands-letter letter-<?php echo $letter; ?>" data-letter="<?php echo $letter; ?>" role="tablist" style="display: block;">
            <dt class="letter" role="tab" aria-selected="true" aria-expanded="true" tabindex="0"><span class="icon-open" data-role="icons" style="display: none;"></span>
                <span class="title"><?php echo $letter; ?></span>
            </dt>
            <dd class="content" role="tabpanel" aria-hidden="false" style="display: block;">
                <ul class="bare-list">
                    <?php
                    if(isset($manufacturerfilter[$letter])){
                    foreach($manufacturerfilter[$letter] as $manu){
                    ?>
                    <li class="brand-item">
                    <a href="<?php echo $manu->getUrl(); ?>" class="item" title="<?php echo $manu->getName(); ?>"><?php echo $manu->getName(); ?></a>
                    </li>
                    <?php
                    }
                    }
                    ?>
                </ul>
            </dd>
        </dl>
    </div>
    <?php
     }
    //  $category = $this->getCategory($item);
    //  echo $category;
    ?>
</div>
<script>
require(['jquery'], function($) {
	$(window).ready(function () {  
		$('.letters-box>.letter').click(function(){
		    $(this).addClass('active');
		    $('.brands-letter').hide();
		    var showid = '.letter-'+ $(this).attr('data-letter');
		    $('.brand-listing').find(showid).show();
		});
		$('.letter-all').click(function(){
		    $('.brands-letter').show();
		    $('.letters-box>.letter').removeClass('active');
		})
	});
	
});
</script>
<style>
    .page-title-wrapper .container .page-title{
        font-size:40px;
        color:#27337e;
        margin:0px;
    }
    .page-title-wrapper .container{
        border-bottom: 5px solid #27337e; 
        margin-bottom:0.7em;
    }
    .brand-listing .brands-letter .title{
        padding: 5px 48px 5px 8px;
        text-transform: uppercase;
        font-weight: 900;
        font-size: 30px;
        background: transparent;
        color: #27337e;
    }
    .brand-searcher{
        background: #27337e;
        padding: 20px;
        box-sizing: border-box;
        width: 100%;
        display: inline-block;
        margin-bottom: 20px;
    }
    .brand-searcher .input-box h3{
        color: white;
        text-align: center;
        margin: 7px auto;
        font-weight: 600;
        text-transform: uppercase;
    }
    .brand-searcher .ambrands-search-wrapper .input-outer {
        position: relative;
    }
    .brand-searcher .ambrands-search-wrapper .ambrands-search-input {
        background-color: #fff;
        padding: 10px;
        height: 44px;
        border-radius: 6px;
    }
    .brands-filters {
        position: relative;
        margin-bottom: 38px;
    }
     .brands-filters .letters-box {
        display: flex;
        flex-basis: auto;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: flex-start;
    }
    .brands-filters .letters-box .letter {
        margin: 0 2px 10px;
        border: 1px solid #e1e5eb;
        background: #e0e6ee;
        color: #1f3a79;
        text-transform: uppercase;
        padding: 5px 10px;
        display: inline-block;
        box-sizing: border-box;
        font-weight: 900;
        font-size: 20px;
    }
    dl{
        margin-top: 0;
        margin-bottom: 20px;
    }
    .brand-listing dl.brands-letter .letter {
        position: relative;
        border-bottom: 3px solid #3157b2;
        font-size: 18px;
        font-weight: 400;
    }
    .brand-listing dd ul.bare-list {
        display: block;
        margin: 40px 0 60px;
        padding-left: 0;
        columns: 4;
        column-gap: 15px;
    }
    .brand-listing dd ul.bare-list li.brand-item {
        margin: 0 0 8px;
    }
    .brand-listing dd ul.bare-list li{
        list-style: none;
    }
    .brand-listing dd ul.bare-list li.brand-item .item {
        display: inline-block;
        font-size: 16px;
        line-height: 1em;
        transition: 400ms;
    }
    .brand-searcher .ambrands-search-wrapper #livesearch {
        top: 39px;
        width: 100%;
        border: none;
        border-radius: 0 0 6px 6px;
        box-shadow: 0 5px 4px 0px rgb(0 0 0 / 20%);
        color: #000;
        float: left;
        position: absolute;
        background: #FFF;
        z-index: 9;
    }
    .brand-searcher .ambrands-search-wrapper #livesearch a {
        color: #000;
        width: 100%;
        float: left;
        padding: 5px;
    }
</style>